// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/advertiseiq-landing/DarkMode.tsx": () => import("../components/mockups/advertiseiq-landing/DarkMode.tsx"),
  "./components/mockups/advertiseiq-landing/LightMode.tsx": () => import("../components/mockups/advertiseiq-landing/LightMode.tsx")
};
